<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250321061330 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA orders');
        $this->addSql('CREATE TABLE orders.order_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT DEFAULT NULL, product_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AED684B18D9F6D38 ON orders.order_items (order_id)');
        $this->addSql('CREATE INDEX IDX_AED684B14584665A ON orders.order_items (product_id)');
        $this->addSql('CREATE TABLE orders.orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, delivery_type VARCHAR(255) NOT NULL, delivery_address JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EA01FA0A76ED395 ON orders.orders (user_id)');
        $this->addSql('ALTER TABLE orders.order_items ADD CONSTRAINT FK_AED684B18D9F6D38 FOREIGN KEY (order_id) REFERENCES orders.orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders.order_items ADD CONSTRAINT FK_AED684B14584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders.orders ADD CONSTRAINT FK_EA01FA0A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_items DROP CONSTRAINT fk_62809db08d9f6d38');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT fk_e52ffdeea76ed395');
        $this->addSql('DROP TABLE order_items');
        $this->addSql('DROP TABLE orders');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE order_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, quantity INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, order_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_62809db08d9f6d38 ON order_items (order_id)');
        $this->addSql('CREATE TABLE orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, delivery_type VARCHAR(255) NOT NULL, delivery_address JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_e52ffdeea76ed395 ON orders (user_id)');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT fk_62809db08d9f6d38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT fk_e52ffdeea76ed395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders.order_items DROP CONSTRAINT FK_AED684B18D9F6D38');
        $this->addSql('ALTER TABLE orders.order_items DROP CONSTRAINT FK_AED684B14584665A');
        $this->addSql('ALTER TABLE orders.orders DROP CONSTRAINT FK_EA01FA0A76ED395');
        $this->addSql('DROP TABLE orders.order_items');
        $this->addSql('DROP TABLE orders.orders');
    }
}
