<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250318074219 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA carts');
        $this->addSql('CREATE TABLE carts.cart_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cart_id INT DEFAULT NULL, product_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ACFB96371AD5CDBF ON carts.cart_items (cart_id)');
        $this->addSql('CREATE INDEX IDX_ACFB96374584665A ON carts.cart_items (product_id)');
        $this->addSql('CREATE TABLE carts.carts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DF49E3A76ED395 ON carts.carts (user_id)');
        $this->addSql('ALTER TABLE carts.cart_items ADD CONSTRAINT FK_ACFB96371AD5CDBF FOREIGN KEY (cart_id) REFERENCES carts.carts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE carts.cart_items ADD CONSTRAINT FK_ACFB96374584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE carts.carts ADD CONSTRAINT FK_2DF49E3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT fk_bef484451ad5cdbf');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT fk_bef484454584665a');
        $this->addSql('ALTER TABLE carts DROP CONSTRAINT fk_4e004aaca76ed395');
        $this->addSql('DROP TABLE cart_items');
        $this->addSql('DROP TABLE carts');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cart_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT DEFAULT NULL, quantity INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cart_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_bef484454584665a ON cart_items (product_id)');
        $this->addSql('CREATE INDEX idx_bef484451ad5cdbf ON cart_items (cart_id)');
        $this->addSql('CREATE TABLE carts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_4e004aaca76ed395 ON carts (user_id)');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT fk_bef484451ad5cdbf FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT fk_bef484454584665a FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE carts ADD CONSTRAINT fk_4e004aaca76ed395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE carts.cart_items DROP CONSTRAINT FK_ACFB96371AD5CDBF');
        $this->addSql('ALTER TABLE carts.cart_items DROP CONSTRAINT FK_ACFB96374584665A');
        $this->addSql('ALTER TABLE carts.carts DROP CONSTRAINT FK_2DF49E3A76ED395');
        $this->addSql('DROP TABLE carts.cart_items');
        $this->addSql('DROP TABLE carts.carts');
    }
}
